// Regenerates src/lib/rules/spec.generated.ts from types.ts. The AI translator
// sends this text to the model as the definition of the rule language, so the
// model always sees exactly the types the validator and compiler implement.
// validate.test.ts fails if the two drift apart. Run: npx tsx scripts/gen-rule-spec.ts
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const dir = join(__dirname, "..", "src", "lib", "rules");
const source = readFileSync(join(dir, "types.ts"), "utf8").replace(/\r\n/g, "\n");
writeFileSync(
  join(dir, "spec.generated.ts"),
  `// Generated by scripts/gen-rule-spec.ts from types.ts. Do not edit.\nexport const RULE_LANGUAGE_SPEC = ${JSON.stringify(source)};\n`
);
